# test binder
name: emri-fom
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scipy
  - ipywidgets
  - h5py
  - astropy
  - healpy
  - jupyter
  - notebook
  - jupyterlab
